dist: xenial
language: cpp
compiler: clang
addons:
    apt:
        packages:
        - libboost-test-dev
        - libspdlog-dev
script:
- cmake .
- cmake --build .
- cmake --build . --target test
- cmake --build . --target package
deploy:
    provider: script
    skip_cleanup: true
    script:
    - curl -T $TRAVIS_BRANCH-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb -uandrewbudo:$BINTRAY_API_KEY "https://api.bintray.com/content/andrewbudo/testing_system/$TRAVIS_BRANCH/$TRAVIS_BUILD_NUMBER/$TRAVIS_BRANCH-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb;deb_distribution=xenial;deb_component=main;deb_architecture=amd64;publish=1"
    on:
      all_branches: true